### ISSUE TITLE
Status of Alkatra

### ISSUE THREAD

**Issue by yanone** [suman51284/Alkatra#2]
Hello Suman (?)

I contacted you here because I have no other contact information. Please feel free to reply here or by email to post@yanone.de

I have been commission to look at Alkatra and how it can be prepared for publication on Google Fonts. It's marked on my list as work still being done on your side. Is that correct? What is the status?

And could you please point me to the latest source for each of the four scripts? I want to look into combining the four scripts into one Glyphs.app source file going forward.

Thanks & best regards,
Yanone

**Comment by yanone** [comment]
Bumping for visibility...

**Comment by yanone** [comment]
Bumping for visibility...

**Comment by suman51284** [comment]
Hello Yanone,
I write to you to enquire about the status of the Alkatra release.

**Comment by yanone** [comment]
Hello, great to hear from you. 
As you can see above, _I_ asked _you_ about the status of Alkatra and never received an answer.

Is all work done on your side?
Which are the latest sources I should be looking at? There are too many sources.

Thank you.

**Comment by suman51284** [comment]
Yanone,
From the folder "Final Files" I am sharing below the link to the files for each script. Hope this clears up your confusion.

Bengali: https://github.com/suman51284/Alkatra/tree/master/Sources/Final%20files/Alkatra_Bangla
Devanagari: https://github.com/suman51284/Alkatra/tree/master/Sources/Final%20files/Alkatra_Devanagari
Latin: https://github.com/suman51284/Alkatra/tree/master/Sources/Final%20files/Alkatra_Latin
Odia: https://github.com/suman51284/Alkatra/tree/master/Sources/Final%20files/Alkatra_Odia

**Comment by yanone** [comment]
If I compile the features of the Odia font, I get the following error:

```
Fehler: »Glyph "nya" not in font.« im Feature blwf in Zeile: 36
Fehler: »Glyph "oriya.base" not in font.« im Feature blwf in Zeile: 36
```
(Sorry for the German language bits).

Please fix this before I can continue. I'm no expert in Indic languages, so I can only work on the fonts when the glyph coverage and OpenType features are in perfect shape.
Thanks for your help.

You can check for yourself by clicking the "Test" button in the Font Info window in Glyphs.app.

**Comment by suman51284** [comment]
Ok! I will try to fix them and upload the latest version very soon.

I completely understand your issues of not knowing the language Scripts. No problems with the German bits either. :)

**Comment by suman51284** [comment]
Hi Yanone,
I have updated the Odia with the fixes. Please have a look into it and let me know if you further face any other issues.

Cheers

**Comment by yanone** [comment]
Hi Suman. Thank you for your updates. I combined the four fonts into one single source (Alkatra.glyphs) and they generate without errors and without failures from our technical test suite "fontbakery".

Please accept [the PR](https://github.com/suman51284/Alkatra/pull/3) that I'm sending you separately.

However, when manually comparing the rendering to macOS system fonts, I found a few problems with all three of the Indic languages and I need you to look over them:

# 1.

While some marks show okay, others create a gap in the word where they're not supposed to. These marks are "non-spacing", and they really need to have a width of 0. I found that the non-spacing in the font have positive width. I've marked these in red in the Glyphs source.

Also, many letters are missing "top" and "bottom" anchors, resulting in bad placement of marks (see second screenshot, right). The base letter in that example is missing a "top" anchor. However, it's possible that once you reset the width of those marks to 0 that the problem of bad placement goes away. Do that first, then see if base letters need more anchors.

For explanation: If you've generated the fonts directly with Glyphs until now, it's possible that Glyphs reduces their width to 0 automatically upon export. But the open-source toolchain that we use to generate fonts doesn't do that, so it needs to be done manually in the source file, which is good practice anyway.

<img width="423" alt="Bildschirmfoto 2022-11-01 um 14 51 31" src="https://user-images.githubusercontent.com/175386/199252965-48100567-fb39-4e0f-8db9-e89b757a0f36.png">
<img width="711" alt="Bildschirmfoto 2022-11-01 um 14 36 13" src="https://user-images.githubusercontent.com/175386/199252970-14e4f90e-cf91-4a18-ad7d-53872ad44121.png">
<img width="393" alt="Bildschirmfoto 2022-11-01 um 14 53 00" src="https://user-images.githubusercontent.com/175386/199252972-cb25ac88-894d-4e28-9cde-a1e8da6b3355.png">

# 2.

I might be wrong here, but this glyph (red) looks like it's too loose on the right.

<img width="524" alt="Bildschirmfoto 2022-11-01 um 14 57 21" src="https://user-images.githubusercontent.com/175386/199252974-510fab44-51a9-41a1-b473-35acacb5e17f.png">

# 3.

This letter is surely wrong as well. I've marked it and its neighbors in orange. Please go over all those and make sure they're okay.

<img width="453" alt="Bildschirmfoto 2022-11-01 um 15 01 30" src="https://user-images.githubusercontent.com/175386/199252977-4c8014f4-4333-4778-8605-63488e2d365f.png">

# 4.

The rendering here shows a lot more letters than the system font just above it. This might be acceptable for that language. I know that there can be variations in ligatures, but again, I can't read and comprehend it, so I need to ask you to please make sure that this is okay.
(You can click on the image to enlarge)

<img width="2169" alt="Bildschirmfoto 2022-11-01 um 15 05 02" src="https://user-images.githubusercontent.com/175386/199252980-2c5cf81d-ca11-4035-a963-2781977b3943.png">

# Very important

If you make any changes, please only work the the single file (Alkatra.glyphs) from now on and use the old 4 files only for comparison to see if I made any mistakes in copying the content over. (I don't think I did, but you never know)

Thank you.

**Comment by yanone** [comment]
Update: I was thinking a bit further about this, and why the marks are not set to zero during export with out toolchain. It turns out that the problem is in a slightly different place: non-spacing marks need to be defined as such explicitly (see screenshot) in order for our tools set them to zero. Just for your information, you can pull of this dialog for a glyph or several glyphs using Cmd+Alt+i in the font view of Glyphs. 

I've done that and now all marks show correctly. So please ignore issue 1) from above.

<img width="282" alt="Bildschirmfoto 2022-11-01 um 15 57 54" src="https://user-images.githubusercontent.com/175386/199264629-357ffba0-6ad2-4fc3-9cb5-50a8b6bcf31f.png">

<img width="1147" alt="Bildschirmfoto 2022-11-01 um 15 59 20" src="https://user-images.githubusercontent.com/175386/199264684-3b39d5d6-9c3e-4185-a4d3-fafc227deb34.png">

**Comment by suman51284** [comment]
**Issue 1:** Thank you for helping me to fix the nonspacing marks and sharing the shortcut for the dialog box. I am unsure if the specifications changed after switching to Glyphs 3. 

**Issue 2:** The right bearing of the letter Visarga is alright. 
![Screenshot 2022-11-02 at 3 27 06 PM](https://user-images.githubusercontent.com/11287162/199460189-a2350da0-1cf1-4e9a-b078-3b2304d61203.png)
It seems I have lost some kerning values with that letter and other characters as well. I am working on it & will sort it out soon.

**Issue 3:** These are marks(available both in the Bengali and the Odia script) where the letterforms are positioned in between the two parts.

![Screenshot 2022-11-02 at 5 57 13 PM](https://user-images.githubusercontent.com/11287162/199490023-dea00a9d-e685-4ef9-b10d-de33b9db3352.png)
![Screenshot 2022-11-02 at 5 57 40 PM](https://user-images.githubusercontent.com/11287162/199490091-6e76d157-e123-4eb8-ae4f-f87eec5b1e9f.png)

The Font file works well on the online font testing platforms with the desired positioning of the marks. (image below)
![Screenshot 2022-11-02 at 6 04 58 PM](https://user-images.githubusercontent.com/11287162/199491230-ad918221-a2ba-49be-86c3-822f562c5372.png)

 But they do not function when you install the font and use it on Illustrator or InDesign.(image below)
![Screenshot 2022-11-02 at 6 13 19 PM](https://user-images.githubusercontent.com/11287162/199492954-18b4347a-3c61-4526-b436-efadd395ebe1.png)

**Issue 4:** This is also the reason why the Odia text you shared looks to have more characters displayed as they are not combining with the input text.

**Comment by suman51284** [comment]
Hi Yanone,
I have worked on the spacing issues for all the characters in the main file. Please have a look at them and let me know if you come across any further issues.

Thanks

**Comment by yanone** [comment]
Thank you. While I'm reviewing your recent changes, please take the time to fill this form: https://docs.google.com/forms/d/e/1FAIpQLSeMwHN8J213ZaxHrr5lHCrX56HY_NjGrWB8o604g98YxuMrdA/viewform

This information will be used for the designer profile to be displayed on Google Fonts.

**Comment by yanone** [comment]
So, only the issue with the accent remains. I tested this in both FontGoggles as well as Chrome browser, to same result. Baloo Bhaina below for comparison. This looks like there may be some OpenType feature code missing for reordering the glyphs?

Please take another look at this. Thank you.

<img width="1835" alt="Bildschirmfoto 2022-11-15 um 15 22 42" src="https://user-images.githubusercontent.com/175386/201943760-350cdaae-9dda-471b-8666-d495dbe5cabe.png">

**Comment by suman51284** [comment]
Thanks for the update! I will look into it and get back to you shortly.

Cheers.

**Comment by suman51284** [comment]
Did you copy the text from the browser and drop it on AxisPraxis? It seems to work fine on mine. I have used the word ହୋଇଥିଲା and it displays the same on AP

![Screenshot 2022-11-15 at 8 46 13 PM](https://user-images.githubusercontent.com/11287162/201956362-5bbd66b8-b342-472a-b5c4-7b1e93ad332e.png)

**Comment by suman51284** [comment]
https://user-images.githubusercontent.com/11287162/201962774-fe2501d0-cd3f-44a1-89c5-ff90a33e4b3f.mov

This seem to work using the keyboard as well.

**Comment by yanone** [comment]
The word you posted looks fine, but ଗୈରୱ does not

**Comment by suman51284** [comment]
OK got it! Let me get back to you on this.

**Comment by suman51284** [comment]
I have managed to fix it. Please have a look at it and see if things are working at your end. Please let me know if you still come across other issues.

Cheers

**Comment by yanone** [comment]
Looks good, thank you. I will send you a PR soon with some more minor changes and newly generated font binaries, and then I'm ready to send the fonts to Google Fonts.

Please don't forget to fill this form for your designer profile: https://docs.google.com/forms/d/e/1FAIpQLSeMwHN8J213ZaxHrr5lHCrX56HY_NjGrWB8o604g98YxuMrdA/viewform

Thank you.

**Comment by suman51284** [comment]
Great! I am looking forward to it.
I am curious to know if the fonts will be released as one complete file covering the 4 scripts or individually based on the scripts?
I have updated the designer profile already.

Cheers

**Comment by yanone** [comment]
It'll be all in one file, hence the work I did to combine this. Btw, if this was my own repository, I would now delete the four old files in the Sources folder to clear up any confusion around this question. They are no longer needed. The other folder with the older files is still there, and one can dig into the commit history any time to find old and deleted files. But that's totally up to you.

Normally it takes around 2 to 3 weeks before the fonts will be live on Google Fonts from now on. Please be patient. I'm closing this issue now. Thank you for your cooperation.

**Comment by yanone** [comment]
Me again. So our reviewer found a couple more small mistakes, such as wrong order of outlines (equal, brokenbar, just to name two), which I've corrected and will PR to you soon.

Because our warnings also complained about http:// links (instead of https://), I accidentally found that the linked designer URL http://reg-it-bold.com/ shows a bunch of crap as well as porn links. Are you sure this is your website and you want to link to it?
If not, please let me know where to link to. I'll include it in my PR. Thanks.

**Comment by suman51284** [comment]
Hi again! I had to pull down my website because it was hacked last year. I am no longer using the URL. I will remove the URL from the font info and further commit here.

**Comment by yanone** [comment]
I'm currently working on the file. Please refrain from changing the file until my PR to avoid merge conflicts. Just give me a second.
