### ISSUE TITLE
Possible rendering issue with Ra

### ISSUE THREAD

**Issue by yanone** [suman51284/Alkatra#7]
Hi,

I was giving Alkatra one last review and found something which I want to bring to your attention regarding the rendering of the Ra. Please see attached screenshot. Your font differs both from macOS system font (seen in text field) as well as our own Baloo, which I've added for reference.

I need to ask you whether the rendering in your font really is acceptable, or whether this is something that should be addressed. Lacking specific knowledge of the script I can only compare rendering and spot deviations.

Please give this another look.

<img width="688" alt="Bildschirm­foto 2023-01-24 um 11 51 15" src="https://user-images.githubusercontent.com/175386/214274222-f4c39d75-a1d8-4fd2-9020-37d6e01b60ff.png">

**Comment by suman51284** [comment]
HI Yanone, 
I will look into this issue and update you on this shortly. Thanks for flagging this issue.

**Comment by suman51284** [comment]
I have updated the file. Please let me know if the issue still exists.

**Comment by yanone** [comment]
No, nothing changed in the binary font after re-generating it.

Just to be clear: I was expecting the whole letter (marked in red) to appear like in the lower example in the above screenshot (Baloo). Maybe I'm mistaken here and that's not strictly necessary.

However, if this change is indeed what your were aiming for, then it didn't come through. Note that I couldn't see any change in OpenType feature code in your last commit. I did find a glyph called `r-deva` in the source and would have expected that to be addressed in the OpenType code somewhere.

But I don't know whether you can simply replace `ra` and `halant` with `r` (the `nukt` feature already has a similar substitution), or whether this can only happen contextually when followed by certain other glyphs, such as the `ya` in the example of the above screenshot.

<img width="383" alt="Bildschirm­foto 2023-01-24 um 15 05 50" src="https://user-images.githubusercontent.com/175386/214316961-1ceaff83-4d90-4cdf-8b2a-bf2d23375acd.png">

**Comment by suman51284** [comment]
Looking into the way the letters have combined, it can only happen contextually. It seemed that the Ra Nukta was not there in the set and I have tried to add the form to the set. Could you please share the text here so that I can copy it and may have another look into it?

**Comment by yanone** [comment]
Sure: पुर्‍याइएको

**Comment by suman51284** [comment]
I am still trying to figure out why it isn't working. I will update you on this very soon.

**Comment by suman51284** [comment]
![Screenshot 2023-01-25 at 12 19 57 AM](https://user-images.githubusercontent.com/11287162/214528130-6ef9a7e7-be8b-40fe-b236-88ed18e0df59.png)

I have added the shape and tried to update the feature file by editing it. But it is showing the error as mentioned below while I try to export the file. I have updated the file for you to please have a look. 

![Screenshot 2023-01-25 at 12 18 45 AM](https://user-images.githubusercontent.com/11287162/214528400-ca0c4928-35af-4167-821b-a58b4431b569.png)

**Comment by yanone** [comment]
I'm off today. I'll check tomorrow. Thank you.

**Comment by suman51284** [comment]
Sure!

**Comment by yanone** [comment]
I can't find the problem you're describing in your latest sources. (The substitution currently starts with `ra-deva`, not `rr-deva` as in your screenshot.)

So basically it works now, and I confirmed that the same solution with `ZWJ` can be found in other Devanagari fonts. I can't see any other problems at the moment, so we'll proceed with the publication now. We can always react on problems reported by users when they arise and publish an update.
I found another tiny interpolation issue of the dot in `rr-deva` by accident and corrected it and generated the latest font and will PR those back to you now.

Thank you.

**Comment by suman51284** [comment]
Thanks Yanone! The issue was in writing the wrong glyph name in the feature file. It should work well from here on. Thanks for your patience and help!

**Comment by yanone** [comment]
Please merge this PR: https://github.com/suman51284/Alkatra/pull/8

**Comment by yanone** [comment]
I just sent the font to Google Fonts. It normally takes around 2-3 weeks from here before they show up in the live website.
Thank you.

**Comment by suman51284** [comment]
Thank you so much. I will start the promotion in a week's time or so. Will there be any notification before it is live on the website by any chance?
